// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths {
    public static var email: Email {
        Email(path: "/auth/email")
    }

    public struct Email {
        /// Path: `/auth/email`
        public let path: String

        /// Login by email
        public func post(_ body: MoneyTellAPI.AuthEmailRequest) -> Request<MoneyTellAPI.Token> {
            Request(method: "POST", url: path, body: body, id: "authEmail")
        }
    }
}
