// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct AuthEmailRequest: Codable {
    public var email: String
    public var password: String

    public init(email: String, password: String) {
        self.email = email
        self.password = password
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.email = try values.decode(String.self, forKey: "email")
        self.password = try values.decode(String.self, forKey: "password")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(email, forKey: "email")
        try values.encode(password, forKey: "password")
    }
}
