// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Token: Codable {
    public var token: String

    public init(token: String) {
        self.token = token
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.token = try values.decode(String.self, forKey: "token")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(token, forKey: "token")
    }
}
